## Calcuating cost-savings based on derate model predictions

### Model test of interest: Neural Network
* Apply neural network and evaluate using kfold cross validation
* Correct for imbalanced dataset

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier, MLPRegressor

from sklearn.preprocessing import StandardScaler, OneHotEncoder, MaxAbsScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import r2_score, mean_squared_error, root_mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

from sklearn.inspection import PartialDependenceDisplay

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer

import warnings
warnings.filterwarnings("ignore")

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

### Define feature and target columns

In [2]:
## target columns
target_var = ['derate_2_6_hr',
              'derate_6_12_hr',
              'derate_12_24_hr', 
             'total_derates_2_hr', 
             'total_derates_6_hr', 
            'total_derates_12_hr', 
             'total_derates_24_hr']

## Predictor columns
# predict_var= ['year',
#            'month',
#            'weekday',
#               'hour',
 predict_var=['DistanceLtd',
              'EngineTimeLtd',
              'FuelLtd',
              'activeTransitionCount',
              'TurboBoostPressure',
              'AcceleratorPedal',
              'BarometricPressure',
              'CruiseControlSetSpeed',
              'EngineCoolantTemperature',
              'EngineLoad',
              'EngineOilPressure',
              'EngineOilTemperature',
              'EngineRpm',
              'FuelLevel',
              'FuelRate',
              'FuelTemperature',
              'IntakeManifoldTemperature',
              'Speed',
              'SwitchedBatteryVoltage',
              'Throttle',
              'active',
              'CruiseControlActive',
              'IgnStatus',
              'ParkingBrake',
              'spn',
              'fmi',
              'min_since_last_fault',
              'EquipmentID',
              'eventDescription',
              'LampStatus']

---

### cost prediction
* merge y_pred back with main dataset, and see if y_pred aligns with y_test and group by equipment and timewindow

In [3]:
#Neural network model application and view classification report
nn_pipe = Pipeline(
steps = [
    ('model', MLPClassifier(random_state=321, 
                            max_iter=5000, 
                            hidden_layer_sizes = (25,25,25), 
                            activation='relu', 
                           early_stopping=True, 
                           solver='adam'))
])

### Open up files for model: for k-fold evaluatuion, open up each test and validation dataset sequentially

In [4]:
#define final dataset to save results
model_evaluation_results= pd.DataFrame(columns=['target_var', 'fold_num', 'total_cost', 'total_pred_derate', 'total actual derate', 'f1-score'])


k_fold_num= [1, 2]
##iteration 1: open each csv file for each fold 
for fold in k_fold_num:
    fold_num = fold
    print(f"Applying k-fold number {fold}")
    
    #open train dataset csv file
    train_data= pd.read_csv(f'../processed_data/train_set_{fold}.csv')
    #open validation dataset csv file 
    val_data= pd.read_csv(f'../processed_data/val_set_{fold}.csv')

    #Iterate 2: apply model to each of the 7 possible target columns 
    for col_num in range(len(target_var)):
        #Select ONE target variable 
        target_var_opt = target_var[col_num]
        ##change the target columns to binary based on the target column selected
        train_data[train_data[target_var_opt]!= 0]=1
        
        #define columns to drop from X dataframes 
        drop_col= target_var + ['EquipmentID', 'EventTimeStamp']
        
        #Prepare train and test variables from the datasets 
        X_train = train_data.drop(columns=drop_col)
        #save model and event time separately 
        X_train_modeltime= train_data[['EquipmentID', 'EventTimeStamp']]
        #save target column as y_train
        y_train= train_data[target_var_opt].astype(int)
        
        #Prepare train and test variables from the datasets 
        X_test = val_data.drop(columns=drop_col)
        #save model and event time separately 
        X_val_modeltime= val_data[['EquipmentID', 'EventTimeStamp']]
        #save target column as y_train
        y_test= val_data[target_var_opt].astype(int)

        #Use SMOTE to over sample the minroity class and under sample the majority class 
        # Apply SMOTE only to training--> OVERSAMPLE minority class
        smote = SMOTE(random_state=321, sampling_strategy=0.1)
        X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
        
        nn_pipe.fit(X_resampled, y_resampled)
        y_pred = nn_pipe.predict(X_test)
        f1_score_eval = classification_report(y_test, y_pred, output_dict=True)['macro avg']['f1-score']

        #calculate cost savings and other metrics
        print(f"calculating model performance for {target_var_opt} on {fold_num}")
        ### save it as a new unqiue dataset name 
        model_calc= X_test
        model_calc['pred_derate']= y_pred
        model_calc['actual_derate']= y_test
        model_calc['EquipmentID'] = X_val_modeltime['EquipmentID']
        model_calc['EventTimeStamp'] = X_val_modeltime['EventTimeStamp']

        ## group by equipment ID and calculate cost and model output metrics 

        model_calc['date']= pd.to_datetime(model_calc['EventTimeStamp']).dt.date
        model_cost_total= model_calc.groupby(['EquipmentID', 'date']).agg({'actual_derate': 'max', 'pred_derate': 'max'}).sort_values('actual_derate', ascending=False)
        
        #create a for loop to calculate cost based on formulas
        total_cost_list = []
        for row in range(len(model_cost_total)):
            eval_row = model_cost_total.iloc[row]
            if eval_row['actual_derate'] == 0 & eval_row['pred_derate'] == 1:
                total_cost_list.append(-500)
            elif eval_row['actual_derate'] == 1 & eval_row['pred_derate'] == 1:
                total_cost_list.append(4000)
            else:
                total_cost_list.append(0)
        
        ## add the final calculation list into the main dataframe 
        model_cost_total['total_cost']= total_cost_list

        ### save cost to final dataframe 
        model_pf = [target_var_opt, 
                    int(fold_num), 
                    model_cost_total['total_cost'].sum(), 
                    model_cost_total['pred_derate'].sum(), 
                    model_cost_total['actual_derate'].sum(), 
                   f1_score_eval]

        model_evaluation_results.loc[len(model_evaluation_results)] = model_pf
        print(f"{target_var_opt} on {fold_num} saved to final dataset")

Applying k-fold number 1
calculating model performance for derate_2_6_hr on 1
derate_2_6_hr on 1 saved to final dataset
calculating model performance for derate_6_12_hr on 1
derate_6_12_hr on 1 saved to final dataset
calculating model performance for derate_12_24_hr on 1
derate_12_24_hr on 1 saved to final dataset
calculating model performance for total_derates_2_hr on 1
total_derates_2_hr on 1 saved to final dataset
calculating model performance for total_derates_6_hr on 1
total_derates_6_hr on 1 saved to final dataset
calculating model performance for total_derates_12_hr on 1
total_derates_12_hr on 1 saved to final dataset
calculating model performance for total_derates_24_hr on 1
total_derates_24_hr on 1 saved to final dataset
Applying k-fold number 2
calculating model performance for derate_2_6_hr on 2
derate_2_6_hr on 2 saved to final dataset
calculating model performance for derate_6_12_hr on 2
derate_6_12_hr on 2 saved to final dataset
calculating model performance for derate_12_24_hr on 2
derate_12_24_hr on 2 saved to final dataset
calculating model performance for total_derates_2_hr on 2
total_derates_2_hr on 2 saved to final dataset
calculating model performance for total_derates_6_hr on 2
total_derates_6_hr on 2 saved to final dataset
calculating model performance for total_derates_12_hr on 2
total_derates_12_hr on 2 saved to final dataset
calculating model performance for total_derates_24_hr on 2
total_derates_24_hr on 2 saved to final dataset

In [5]:
#view final dataframe
model_evaluation_results

,target_var,fold_num,total_cost,total_pred_derate,total actual derate,f1-score
0,derate_2_6_hr,1,0,0,55,0.499769
1,derate_6_12_hr,1,0,0,45,0.499807
2,derate_12_24_hr,1,0,0,107,0.499523
3,total_derates_2_hr,1,0,0,97,0.333163
4,total_derates_6_hr,1,0,0,134,0.249769
5,total_derates_12_hr,1,0,0,157,0.249696
6,total_derates_24_hr,1,0,0,245,0.199591
7,derate_2_6_hr,2,0,0,41,0.499883
8,derate_6_12_hr,2,0,0,16,0.499952
9,derate_12_24_hr,2,0,0,40,0.499801
10,total_derates_2_hr,2,0,0,117,0.249891
11,total_derates_6_hr,2,0,0,146,0.199874
12,total_derates_12_hr,2,0,0,152,0.166550
13,total_derates_24_hr,2,0,0,180,0.166493

---

In [35]:
#Select ONE target variable 
target_var_opt = target_var[0]
##change the target columns to binary based on the target column selected
train_data[train_data[target_var_opt]!= 0]=1

#define columns to drop from X dataframes 
drop_col= target_var + ['EquipmentID', 
                        'EventTimeStamp'] + ['year',
                                             'month',
                                             'weekday',
                                             'hour']

#Prepare train and test variables from the datasets

In [37]:
X_train = train_data#.drop(columns=drop_col)
#save model and event time separately 
X_train_modeltime= train_data[['EquipmentID', 'EventTimeStamp']]
#save target column as y_train
y_train= train_data[target_var_opt].astype(int)

#Prepare train and test variables from the datasets 
X_test = val_data#.drop(columns=drop_col)
#save model and event time separately 
X_val_modeltime= val_data[['EquipmentID', 'EventTimeStamp']]
#save target column as y_train
y_test= val_data[target_var_opt].astype(int)

#Use SMOTE to over sample the minroity class and under sample the majority class 
# Apply SMOTE only to training--> OVERSAMPLE minority class
smote = SMOTE(random_state=321, sampling_strategy=0.1)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

nn_pipe.fit(X_resampled, y_resampled)
y_pred = nn_pipe.predict(X_test)
f1_score_eval = classification_report(y_test, y_pred, output_dict=True)['macro avg']['f1-score']
y_pred_prob = nn_pipe.predict_proba(X_test)

ValueError: could not convert string to float: 'R1762'

In [29]:
y_pred_prob = nn_pipe.predict_proba(X_resampled)

In [31]:
print(confusion_matrix(y_resampled, y_pred_prob[:,1]>0.5)) #, output_dict=True)

[[375714      0]
 [     0  37571]]

In [26]:
y_train.sum()

1828

In [27]:
y_resampled.sum()

37571

In [15]:
y_pred_prob

array([[0.90766051, 0.09233949],
       [0.91956502, 0.08043498],
       [0.9403967 , 0.0596033 ],
       ...,
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ]])

In [ ]:
# #calculate cost savings and other metrics
# print(f"calculating model performance for {target_var_opt} on {fold_num}")
# ### save it as a new unqiue dataset name 
# model_calc= X_test
# model_calc['pred_derate']= y_pred
# model_calc['actual_derate']= y_test
# model_calc['EquipmentID'] = X_val_modeltime['EquipmentID']
# model_calc['EventTimeStamp'] = X_val_modeltime['EventTimeStamp']

# ## group by equipment ID and calculate cost and model output metrics 

# model_calc['date']= pd.to_datetime(model_calc['EventTimeStamp']).dt.date
# model_cost_total= model_calc.groupby(['EquipmentID', 'date']).agg({'actual_derate': 'max', 'pred_derate': 'max'}).sort_values('actual_derate', ascending=False)

# #create a for loop to calculate cost based on formulas
# total_cost_list = []
# for row in range(len(model_cost_total)):
#     eval_row = model_cost_total.iloc[row]
#     if eval_row['actual_derate'] == 0 & eval_row['pred_derate'] == 1:
#         total_cost_list.append(-500)
#     elif eval_row['actual_derate'] == 1 & eval_row['pred_derate'] == 1:
#         total_cost_list.append(4000)
#     else:
#         total_cost_list.append(0)

# ## add the final calculation list into the main dataframe 
# model_cost_total['total_cost']= total_cost_list

# ### save cost to final dataframe 
# model_pf = [target_var_opt, 
#             int(fold_num), 
#             model_cost_total['total_cost'].sum(), 
#             model_cost_total['pred_derate'].sum(), 
#             model_cost_total['actual_derate'].sum(), 
#            f1_score_eval]

# model_evaluation_results.loc[len(model_evaluation_results)] = model_pf
# print(f"{target_var_opt} on {fold_num} saved to final dataset")

In [13]:
nn_pipe.fit(X_resampled, y_resampled)
y_pred_prob = nn_pipe.predict_proba(X_test)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- EquipmentID
- EventTimeStamp
- actual_derate
- date
- pred_derate

-----

### Prepare datasets for train-test split, by removing any columns from the dataset that is NOT used in prediction, and saving the target variable column of interest in the Y value

In [6]:
# #Select ONE target variable 
# target_var_opt = target_var[0]
# ##change the target columns to binary based on the target column selected
# train_data[train_data[target_var_opt]!= 0]=1
# train_data[target_var_opt].value_counts()

# #define columns to drop from X dataframes 
# drop_col= target_var + ['EquipmentID', 'EventTimeStamp']

# #Prepare train and test variables from the datasets 
# X_train = train_data.drop(columns=drop_col)
# #save model and event time separately 
# X_train_modeltime= train_data[['EquipmentID', 'EventTimeStamp']]
# #save target column as y_train
# y_train= train_data[target_var_opt].astype(int)

# #Prepare train and test variables from the datasets 
# X_test = val_data.drop(columns=drop_col)
# #save model and event time separately 
# X_val_modeltime= val_data[['EquipmentID', 'EventTimeStamp']]
# #save target column as y_train
# y_test= val_data[target_var_opt].astype(int)

## Define the model pipeline, train it on the train dataset, and create predictions from the test dataset

In [7]:
# #Neural network model application and view classification report
# nn_pipe = Pipeline(
# steps = [
#     ('model', MLPClassifier(random_state=321, 
#                             max_iter=5000, 
#                             hidden_layer_sizes = (100,100), 
#                             activation='relu', 
#                            early_stopping=True, 
#                            solver='adam'))
# ])

# #Use SMOTE to over sample the minroity class and under sample the majority class 
# # Apply SMOTE only to training--> OVERSAMPLE minority class
# smote = SMOTE(random_state=321, sampling_strategy=0.1)
# X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

# nn_pipe.fit(X_resampled, y_resampled)
# y_pred = nn_pipe.predict(X_test)

# f1_score_eval = classification_report(y_test, y_pred, output_dict=True)['macro avg']['f1-score']

### Add the predicited y_pred back to the full test dataset by adding it as a column, as well as equipment ID and event timestamp

In [8]:
# ### save it as a new unqiue dataset name 
# model_calc= X_test

# model_calc['pred_derate']= y_pred
# model_calc['actual_derate']= y_test
# model_calc['EquipmentID'] = X_val_modeltime['EquipmentID']
# model_calc['EventTimeStamp'] = X_val_modeltime['EventTimeStamp']

# #view dataframe to see column options
# model_calc.head(5)

---

# Calculate the company cost/savings based on model performance
Group by equipmentID and timestamp to get actual v predicted derate differnces

### For each truck, how many false positives did I have for each DAY? 
**For any truck-date combos:**
*  FALSE NEG- IF we failed to predict the derate (pred_derate=0) when an actual derate happened (actual_derate=1) -> no cost added because we already failed to catch it (so company is charged 4000 dollars regardless)
* FALSE POS- If we did predicit a derate (pred_derate = 1) when there was NOT a derate (actual_derate = 0) -> costs 500 dollars
* TRUE POS- IF we sucessfully predicted a derate (pred_derate = 1) when there WAS a derate (actuacl_derate = 1) -> SAVE 4000 dollars

In [9]:
# model_calc['date']= pd.to_datetime(model_calc['EventTimeStamp']).dt.date
# model_cost_total= model_calc.groupby(['EquipmentID', 'date']).agg({'actual_derate': 'max', 'pred_derate': 'max'}).sort_values('actual_derate', ascending=False)

# #create a for loop to calculate cost based on formulas
# total_cost_list = []
# for row in range(len(model_cost_total)):
#     eval_row = model_cost_total.iloc[row]
#     if eval_row['actual_derate'] == 0 & eval_row['pred_derate'] == 1:
#         total_cost_list.append(-500)
#     elif eval_row['actual_derate'] == 1 & eval_row['pred_derate'] == 1:
#         total_cost_list.append(4000)
#     else:
#         total_cost_list.append(0)

# ## add the final calculation list into the main dataframe 
# model_cost_total['total_cost']= total_cost_list

# #view and sort by total_cost per truck event 
# #model_cost_total.sort_values(['total_cost'], ascending=True)
# model_cost_total

# model_pf = [target_var_opt, 
#             int(fold_num), 
#             model_cost_total['total_cost'].sum(), 
#             model_cost_total['pred_derate'].sum(), 
#             model_cost_total['actual_derate'].sum(), 
#             0]

# model_evaluation_results= pd.DataFrame(columns=['target_var', 'fold_num', 'total_cost', 'total_pred_derate', 'total actual derate', 'f1-score'])
# model_evaluation_results.loc[len(model_evaluation_results)] = model_pf
# model_evaluation_results

## Calculate the total cost by adding up all the 'total_cost' columns

In [10]:
# print("total cost: ", model_cost_total['total_cost'].sum())
# print("total predicted derates:", model_cost_total['pred_derate'].sum())
# print("total actual derates:", model_cost_total['actual_derate'].sum())

# #save model performance in a dictionary
# # #model_pf = dict({'target_var': target_var_opt, 
# #       'fold':int(fold_num), 
# #       'total_cost':model_cost_total['total_cost'].sum(), 
# #       'total_pred_derate':model_cost_total['pred_derate'].sum(), 
# #       'total actual derate':model_cost_total['actual_derate'].sum()})

# model_pf = [target_var_opt, 
#             int(fold_num), 
#             model_cost_total['total_cost'].sum(), 
#             model_cost_total['pred_derate'].sum(), 
#             model_cost_total['actual_derate'].sum(), 
#             0]

# model_evaluation_results= pd.DataFrame(columns=['target_var', 'fold_num', 'total_cost', 'total_pred_derate', 'total actual derate', 'f1-score'])
# model_evaluation_results.loc[len(model_evaluation_results)] = model_pf
# model_evaluation_results

---

In [72]:
target_var

['derate_2_6_hr',
 'derate_6_12_hr',
 'derate_12_24_hr',
 'total_derates_2_hr',
 'total_derates_6_hr',
 'total_derates_12_hr',
 'total_derates_24_hr']

In [113]:
#Neural network model application and view classification report
nn_pipe = Pipeline(
steps = [
    ('model', MLPClassifier(random_state=321, 
                            max_iter=5000, 
                            hidden_layer_sizes = (25,25,25), 
                            activation='tanh', 
                           early_stopping=True, 
                           solver='adam'))
])

In [131]:
# k_fold_num= [1]
# ##iteration 1: open each csv file for each fold 
# for fold in k_fold_num:
#     fold_num = fold
#     print(f"Applying k-fold number {fold}")

#open train dataset csv file
train_data= pd.read_csv(f'../processed_data/train_set_2.csv')
#open validation dataset csv file 
val_data= pd.read_csv(f'../processed_data/train_set_2.csv')

#Iterate 2: apply model to each of the 7 possible target columns 
#for col_num in range(len(target_var)):
#Select ONE target variable 
target_var_opt = target_var[0]
##change the target columns to binary based on the target column selected
#train_data[train_data[target_var_opt]!= 0]=1

drop_col= target_var + ['EquipmentID', 'EventTimeStamp', 'month_sin__month','month_cos__month','weekday_sin__weekday','weekday_cos__weekday','hour_sin__hour','hour_cos__hour', 'Unnamed: 0', 'year']
#Prepare train and test variables from the datasets 
X_train = train_data.drop(columns=drop_col)
#save model and event time separately 
X_train_modeltime= train_data[['EquipmentID', 'EventTimeStamp']]
#save target column as y_train
y_train= train_data[target_var_opt].astype(int)

#Prepare train and test variables from the datasets 
X_test = val_data.drop(columns=drop_col)
#save model and event time separately 
X_val_modeltime= val_data[['EquipmentID', 'EventTimeStamp']]
#save target column as y_train
y_test= val_data[target_var_opt].astype(int)

#Use SMOTE to over sample the minroity class and under sample the majority class 
# Apply SMOTE only to training--> OVERSAMPLE minority class
smote = SMOTE(random_state=321, sampling_strategy=0.1)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

In [141]:
nn_pipe.fit(X_train, y_train)

Pipeline(steps=[('model',
                 MLPClassifier(activation='tanh', early_stopping=True,
                               hidden_layer_sizes=(25, 25, 25), max_iter=5000,
                               random_state=321))])

In [143]:
X_train.columns.to_list()

['min_since_last_fault',
 'DistanceLtd',
 'EngineTimeLtd',
 'FuelLtd',
 'activeTransitionCount',
 'TurboBoostPressure',
 'AcceleratorPedal',
 'BarometricPressure',
 'CruiseControlSetSpeed',
 'EngineCoolantTemperature',
 'EngineLoad',
 'EngineOilPressure',
 'EngineOilTemperature',
 'EngineRpm',
 'FuelLevel',
 'FuelRate',
 'FuelTemperature',
 'IntakeManifoldTemperature',
 'Speed',
 'SwitchedBatteryVoltage',
 'Throttle',
 'LampStatus_0',
 'LampStatus_1023',
 'LampStatus_11',
 'LampStatus_1279',
 'LampStatus_16639',
 'LampStatus_16895',
 'LampStatus_17407',
 'LampStatus_17663',
 'LampStatus_18419',
 'LampStatus_18431',
 'LampStatus_2',
 'LampStatus_2035',
 'LampStatus_2047',
 'LampStatus_21503',
 'LampStatus_22527',
 'LampStatus_255',
 'LampStatus_4351',
 'LampStatus_50175',
 'LampStatus_511',
 'LampStatus_5119',
 'LampStatus_51199',
 'LampStatus_5375',
 'LampStatus_6143',
 'LampStatus_617',
 'LampStatus_62463',
 'LampStatus_63487',
 'LampStatus_65535',
 'LampStatus_9',
 'spn_0.0',
 'spn_100.0',
 'spn_101.0',
 'spn_102.0',
 'spn_1024.0',
 'spn_1028.0',
 'spn_103.0',
 'spn_1045.0',
 'spn_105.0',
 'spn_1056.0',
 'spn_1059.0',
 'spn_1067.0',
 'spn_1068.0',
 'spn_1072.0',
 'spn_1073.0',
 'spn_1078.0',
 'spn_110.0',
 'spn_111.0',
 'spn_1172.0',
 'spn_1176.0',
 'spn_1209.0',
 'spn_1231.0',
 'spn_1236.0',
 'spn_1247.0',
 'spn_1279.0',
 'spn_1322.0',
 'spn_1323.0',
 'spn_1324.0',
 'spn_1325.0',
 'spn_1326.0',
 'spn_1327.0',
 'spn_1328.0',
 'spn_1347.0',
 'spn_1481.0',
 'spn_1482.0',
 'spn_1483.0',
 'spn_1569.0',
 'spn_157.0',
 'spn_1668.0',
 'spn_1675.0',
 'spn_168.0',
 'spn_17096.0',
 'spn_171.0',
 'spn_175.0',
 'spn_17590.0',
 'spn_1761.0',
 'spn_177.0',
 'spn_1787.0',
 'spn_1807.0',
 'spn_1808.0',
 'spn_1809.0',
 'spn_1815.0',
 'spn_184.0',
 'spn_188.0',
 'spn_190.0',
 'spn_2017.0',
 'spn_2023.0',
 'spn_235.0',
 'spn_236.0',
 'spn_245.0',
 'spn_247.0',
 'spn_248.0',
 'spn_256.0',
 'spn_25780.0',
 'spn_2579.0',
 'spn_2623.0',
 'spn_2629.0',
 'spn_2659.0',
 'spn_27.0',
 'spn_2791.0',
 'spn_2795.0',
 'spn_2863.0',
 'spn_2866.0',
 'spn_29902.0',
 'spn_3031.0',
 'spn_3058.0',
 'spn_3060.0',
 'spn_3064.0',
 'spn_3216.0',
 'spn_3217.0',
 'spn_3218.0',
 'spn_3226.0',
 'spn_3228.0',
 'spn_3241.0',
 'spn_3242.0',
 'spn_3245.0',
 'spn_3246.0',
 'spn_3249.0',
 'spn_3251.0',
 'spn_3253.0',
 'spn_32894.0',
 'spn_3360.0',
 'spn_3361.0',
 'spn_3362.0',
 'spn_3363.0',
 'spn_3364.0',
 'spn_3464.0',
 'spn_3480.0',
 'spn_3482.0',
 'spn_3490.0',
 'spn_3509.0',
 'spn_3510.0',
 'spn_3511.0',
 'spn_3513.0',
 'spn_3514.0',
 'spn_35527.0',
 'spn_3556.0',
 'spn_3584.0',
 'spn_3597.0',
 'spn_36017.0',
 'spn_3605.0',
 'spn_3610.0',
 'spn_3663.0',
 'spn_3695.0',
 'spn_3697.0',
 'spn_3698.0',
 'spn_37.0',
 'spn_3703.0',
 'spn_3720.0',
 'spn_37265.0',
 'spn_3821.0',
 'spn_3936.0',
 'spn_4094.0',
 'spn_4096.0',
 'spn_411.0',
 'spn_412.0',
 'spn_42190.0',
 'spn_4276.0',
 'spn_43088.0',
 'spn_4334.0',
 'spn_4339.0',
 'spn_4340.0',
 'spn_4342.0',
 'spn_4344.0',
 'spn_4346.0',
 'spn_4354.0',
 'spn_4360.0',
 'spn_4363.0',
 'spn_4364.0',
 'spn_4375.0',
 'spn_4376.0',
 'spn_444.0',
 'spn_4607.0',
 'spn_46262.0',
 'spn_47284.0',
 'spn_4752.0',
 'spn_4765.0',
 'spn_4794.0',
 'spn_4796.0',
 'spn_4811.0',
 'spn_5019.0',
 'spn_5024.0',
 'spn_5031.0',
 'spn_50353.0',
 'spn_5113.0',
 'spn_512.0',
 'spn_51923.0',
 'spn_520200.0',
 'spn_520203.0',
 'spn_520298.0',
 'spn_520302.0',
 'spn_520330.0',
 'spn_523530.0',
 'spn_523531.0',
 'spn_523543.0',
 'spn_524033.0',
 'spn_524037.0',
 'spn_524287.0',
 'spn_5246.0',
 'spn_5298.0',
 'spn_5319.0',
 'spn_5394.0',
 'spn_53958.0',
 'spn_5396.0',
 'spn_5397.0',
 'spn_5442.0',
 'spn_5443.0',
 'spn_5444.0',
 'spn_54478.0',
 'spn_5491.0',
 'spn_5571.0',
 'spn_558.0',
 'spn_5585.0',
 'spn_563.0',
 'spn_56503.0',
 'spn_5742.0',
 'spn_5743.0',
 'spn_576.0',
 'spn_578.0',
 'spn_5848.0',
 'spn_5851.0',
 'spn_5853.0',
 'spn_5862.0',
 'spn_596.0',
 'spn_609.0',
 'spn_611.0',
 'spn_612.0',
 'spn_614.0',
 'spn_6146.0',
 'spn_624.0',
 'spn_627.0',
 'spn_629.0',
 'spn_630.0',
 'spn_632.0',
 'spn_636.0',
 'spn_639.0',
 'spn_641.0',
 'spn_647.0',
 'spn_649.0',
 'spn_651.0',
 'spn_652.0',
 'spn_65287.0',
 'spn_653.0',
 'spn_654.0',
 'spn_655.0',
 'spn_65535.0',
 'spn_656.0',
 'spn_677.0',
 'spn_70.0',
 'spn_723.0',
 'spn_768.0',
 'spn_77.0',
 'spn_788.0',
 'spn_789.0',
 'spn_790.0',
 'spn_791.0',
 'spn_792.0',
 'spn_793.0',
 'spn_794.0',
 'spn_795.0',
 'spn_797.0',
 'spn_798.0',
 'spn_799.0',
 'spn_800.0',
 'spn_801.0',
 'spn_802.0',
 'spn_803.0',
 'spn_806.0',
 'spn_807.0',
 'spn_81.0',
 'spn_810.0',
 'spn_811.0',
 'spn_829.0',
 'spn_84.0',
 'spn_862.0',
 'spn_886.0',
 'spn_905.0',
 'spn_907.0',
 'spn_91.0',
 'spn_917.0',
 'spn_929.0',
 'spn_94.0',
 'spn_95.0',
 'spn_96.0',
 'spn_97.0',
 'spn_98.0',
 'fmi_0.0',
 'fmi_1.0',
 'fmi_10.0',
 'fmi_11.0',
 'fmi_12.0',
 'fmi_13.0',
 'fmi_14.0',
 'fmi_15.0',
 'fmi_16.0',
 'fmi_17.0',
 'fmi_18.0',
 'fmi_19.0',
 'fmi_2.0',
 'fmi_20.0',
 'fmi_21.0',
 'fmi_23.0',
 'fmi_3.0',
 'fmi_31.0',
 'fmi_4.0',
 'fmi_5.0',
 'fmi_6.0',
 'fmi_7.0',
 'fmi_8.0',
 'fmi_9.0',
 'active_False',
 'active_True',
 'CruiseControlActive_False',
 'CruiseControlActive_True',
 'IgnStatus_False',
 'IgnStatus_True',
 'ParkingBrake_False',
 'ParkingBrake_True']

In [142]:
y_pred_prob = nn_pipe.predict_proba(X_train)#X_test[X_train.columns])
print(confusion_matrix(y_train, y_pred_prob[:,1]>0.5)) #, output_dict=True)

[[188568      0]
 [   203      0]]

In [125]:
from sklearn.inspection import permutation_importance

In [126]:
# X_resampled, y_resampled

In [127]:
print(confusion_matrix(y_train.sample(n=10000, random_state=321), nn_pipe.predict(X_train.sample(n=10000, random_state=321))))

[[9988    0]
 [  12    0]]

In [103]:
perm_mean = permutation_importance(nn_pipe, 
                                   X_train.sample(n=10000, random_state=321), 
                                   y_train.sample(n=10000, random_state=321),
                                   n_repeats=10,
                                random_state=321, 
                                   scoring='f1')['importances_mean']
col_feature = X_train.columns.to_list()

pd.DataFrame({
    'variable': col_feature,
    'importance':perm_mean
}).sort_values('importance', ascending = True)

                 variable  importance
0    min_since_last_fault         0.0
254            spn_5491.0         0.0
253           spn_54478.0         0.0
252            spn_5444.0         0.0
251            spn_5443.0         0.0
..                    ...         ...
120             spn_236.0         0.0
119             spn_235.0         0.0
118            spn_2023.0         0.0
127             spn_256.0         0.0
374     ParkingBrake_True         0.0

[375 rows x 2 columns]

In [ ]:
#Neural network model application and view classification report
nn_pipe = Pipeline(
steps = [
    ('model', MLPClassifier(random_state=321, 
                            max_iter=5000, 
                            hidden_layer_sizes = (25,25,25), 
                            activation='relu', 
                           early_stopping=True, 
                           solver='adam'))
])

In [104]:
pd.DataFrame({
    'variable': col_feature,
    'importance':perm_mean
}).sort_values('importance', ascending = False)

                 variable  importance
0    min_since_last_fault         0.0
247           spn_53958.0         0.0
256             spn_558.0         0.0
255            spn_5571.0         0.0
254            spn_5491.0         0.0
..                    ...         ...
123             spn_247.0         0.0
122             spn_245.0         0.0
121             spn_237.0         0.0
120             spn_236.0         0.0
374     ParkingBrake_True         0.0

[375 rows x 2 columns]

In [107]:
perm_mean

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [100]:
pd.DataFrame({
    'variable': col_feature,
    'importance':perm_mean
}).sort_values('importance', ascending = True)

                 variable  importance
0    min_since_last_fault         0.0
254            spn_5491.0         0.0
253           spn_54478.0         0.0
252            spn_5444.0         0.0
251            spn_5443.0         0.0
..                    ...         ...
120             spn_236.0         0.0
119             spn_235.0         0.0
118            spn_2023.0         0.0
127             spn_256.0         0.0
374     ParkingBrake_True         0.0

[375 rows x 2 columns]